- name: Move files to server
  become: true
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
    

- name: Install
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    
- name: Build
  become: true
  shell: | 
    cd /home/ubuntu/backend
    npm run build
    
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
